kind: pipeline
name: default
type: kubernetes

steps:
- name: mirroring_github.in
  pull: always
  image: j33r/git-mirror:latest
  failure: ignore
  environment:
    GIT_MIRROR_USER: jee
    GIT_MIRROR_TOKEN:
      from_secret: GITHUB_TOKEN
    GIT_MIRROR_REPO: github.com/jee-r/pigePy.git
  when:
    branch:
      - master
      - dev
    event:
      exclude:
        - pull_request

- name: mirroring_framagit
  pull: always
  image: j33r/git-mirror:latest
  failure: ignore
  environment:
    GIT_MIRROR_USER: jee
    GIT_MIRROR_TOKEN:
      from_secret: FRAMAGIT_TOKEN
    GIT_MIRROR_REPO: framagit.org/quetsch/pigePy.git
  when:
    branch:
      - master
      - dev
    event:
      exclude:
        - pull_request
